stages:
  - build
  - test 
  - push_to_dockerhub
  - deploy

build_job:
  stage: build
  script:
    - docker build -t frontend:latest /home/sahmad/mazon-comerce-microservices-application/front-end
  tags:
    - ecommerce_dev

test_job:
  stage: test
  script:
    - echo "testing"
  tags:
    - ecommerce_dev

push_job:
  stage: push_to_dockerhub
  script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
    - docker image tag frontend:latest "$DOCKERHUB_USER/frontend:latest"
    - docker push "$DOCKERHUB_USER/frontend:latest"
  tags:
    - ecommerce_dev

deploy_job:
  stage: deploy
  script:
    - kubectl apply -f deployment/secret.yml
    - kubectl apply -f deployment/configmap-frontend.yml
    - kubectl apply -f deployment/ingress.yml
    - kubectl apply -f deployment/deployment-app.yml
    - kubectl apply -f deployment/service-app.yml
  tags:
    - ecommerce_dev

